### ISSUE TITLE
Pixel4目标ROM不支持

### ISSUE THREAD

**Issue by asdf1210** [RiwiHow/FixChinaCarrier#10]
![Screenshot_20210622-122430](https://user-images.githubusercontent.com/79083674/122863271-10a71b80-d355-11eb-8b04-97899be30216.png)
![Screenshot_20210622-123042](https://user-images.githubusercontent.com/79083674/122863639-bbb7d500-d355-11eb-817d-647686cf88e7.png)

**Comment by asdf1210** [comment]
这个是log文件，谢谢大佬帮忙
https://drive.google.com/file/d/131tvCHmWWgPM2rHt5vRTdJDRE6jxPCip/view?usp=drivesdk

**Comment by RiwiHow** [comment]
Pixel 的 APN 配置文件似乎是在一个应用中，搞不了……
（这个模块就是替换在 `/system/etc` 或者 `/system/vendor/etc` 或者 `/system/product/etc` 下的 `apns-conf.xml` 文件）

**Comment by asdf1210** [comment]
好吧，谢谢大佬哈

**Comment by asdf1210** [comment]
我的pixel4刷机和刷了基带插卡还是用不了，但是插卡可以显示是被运营商，但是就是打电话和短信流量用不了。

**Comment by RiwiHow** [comment]
> 我的 pixel4 刷机和刷了基带插卡还是用不了，但是插卡可以显示是被运营商，但是就是打电话和短信流量用不了。

抱歉，这个不清楚 🤔

**Comment by asdf1210** [comment]
好的，谢谢啦

**Comment by liuhjhj** [comment]
同Pixel，真他妈难受啊，电信网络差的一笔

**Comment by KingFalse** [comment]
pixel 7 pro
也是一样提示不支持

**Comment by RiwiHow** [comment]
> pixel 7 pro
> 也是一样提示不支持

这个模块是支持不了 Pixel 的。因为似乎 Pixel 把 APN 的配置文件写在了一个应用中 😢
