### ISSUE TITLE
好久没有更新了

### ISSUE THREAD

**Issue by Mixlining** [RiwiHow/FixChinaCarrier#11]
是否有计划更新一波apn.xml?

**Comment by RiwiHow** [comment]
> 是否有计划更新一波 apn.xml?

没问题，只不过我感觉不更新似乎也没啥问题。刚好最近买了个小米平板 5，等能解锁了（168 小时还没到），我去提取文件更新一下。

**Comment by RiwiHow** [comment]
> 是否有计划更新一波 apn.xml?

没问题，只不过我感觉不更新似乎也没啥问题。刚好最近买了个小米平板 5，等能解锁了（168 小时还没到），我去提取文件更新一下。

话说好久没写了，都忘记 Git 怎么操作了 😣

**Comment by RiwiHow** [comment]
> 是否有计划更新一波 apn.xml?

新版发布了，请去 [Releases](https://github.com/RiwiHow/FixChinaCarrier/releases/tag/v5.3.2) 查看！ 😆

**Comment by Mixlining** [comment]
太好了,谢谢开发者大大

**Comment by ASC8384** [comment]
请问2025年有更新的必要吗？

**Comment by RiwiHow** [comment]
> 请问2025年有更新的必要吗？

两年没用过原生 Android 了，不清楚现在是不是都没这个问题了...只要使用网速不会只有几 KB 就说明没这个问题

而且，这个自己也好更新，提取一个 `apns-conf.xml` 替换原代码里面的就可以（`/APN/apns-conf.xml`）
