### ISSUE TITLE
K30P AEX显示目标ROM不支持

### ISSUE THREAD

**Issue by Roiyaru** [RiwiHow/FixChinaCarrier#7]
模块已经自动导出log
https://mega.nz/file/BPI1CI6C#0J3_VIZXkdlXcujtRbCTuZtfkvWT3JSvdh1FmVbFrmc

**Comment by RimuruW** [comment]
请问在 `/system` 文件夹下是否存在名为 `apns-conf.xml` 的文件？

如果存在，请完成如下操作
- 提供文件完整路径，形如 `/system/etc/apns-conf.xml`
- 提供 Magisk Manager 模块刷入界面的截图

如果不存在，请先在 `/system` 下全局搜索，看看是否存在名称含`apn`的文件，并检查软件列表中是否有包名含 `carrier` 字符串的软件。
如果有，请尽量提供以下信息
- 名称含`apn`的文件的完整路径
- 包名含`carrier`的软件包的包名及截图

目前已知部分 ROM 会从某特定的系统软件中读取 APN 配置信息并强制重写独立的 APN 配置文件，但由于目前无人提供相关信息因此无法进行进一步的确认。因此，我们预计于下一个测试版本提供更完善的日志抓取功能。如果你不知道该怎么做，可以等待下一个测试版本，我们会在下一个测试版本 release 的时候通知你。

**Comment by Roiyaru** [comment]
十分抱歉，我已经刷回MIUI系统，无法协助。但我会尝试邀请别人协助。

**Comment by RimuruW** [comment]
没事，你会回原生的，我对 MIUI 很有自信。
