### ISSUE TITLE
一加8t crdroid显示不支持

### ISSUE THREAD

**Issue by bluboy-official** [RiwiHow/FixChinaCarrier#8]
rt 附log
[unsupportedrom-debug.log](https://github.com/RiwiHow/FixChinaCarrier/files/6287843/unsupportedrom-debug.log)

**Comment by RiwiHow** [comment]
> rt 附 log
> [unsupportedrom-debug.log](https://github.com/RiwiHow/FixChinaCarrier/files/6287843/unsupportedrom-debug.log)

能否发送一下「APN 设置」的截图？谢谢！

**Comment by bluboy-official** [comment]
![Screenshot_20210414-102419_设置](https://user-images.githubusercontent.com/56422076/114645288-bca40900-9d0b-11eb-8573-c999132eb9ce.png)
![Screenshot_20210414-102401_设置](https://user-images.githubusercontent.com/56422076/114645293-bf066300-9d0b-11eb-97b6-88e683becaf9.png)
rt
其实和正常的类原生没区别啊😂不知道为什么就不行x

**Comment by RiwiHow** [comment]
> ![Screenshot_20210414-102419_设置](https://user-images.githubusercontent.com/56422076/114645288-bca40900-9d0b-11eb-8573-c999132eb9ce.png)
> ![Screenshot_20210414-102401_设置](https://user-images.githubusercontent.com/56422076/114645293-bf066300-9d0b-11eb-97b6-88e683becaf9.png)
> rt
> 其实和正常的类原生没区别啊😂不知道为什么就不行 x

把「中国电信」的改成 `ctnet`；把「中国联通」的改成第一个 `3gnet` 看看

**Comment by bluboy-official** [comment]
试了 连不上惹 然后也同样装不上模块x

**Comment by RiwiHow** [comment]
> 试了 连不上惹 然后也同样装不上模块 x

好吧……
这个模块是寻找 `/etc/apns-conf.xml` 或者 `/product/apns-conf.xml` 或者 `/vendor/apns-conf.xml`，并把它们替换成模块中的 `apns-conf.xml`。

你这边装不上要么是因为 `apns-conf.xml` 放在了别的目录，要么是读取的一个软件中的 `apns-conf.xml`。你可以搜索一下带有 `carrier` 字样的软件，看看里面是不是有这个文件。

**Comment by bluboy-official** [comment]
ok 我看一下再回你x

**Comment by D-Bood** [comment]
我刷了crdroid、fluid，这几个rom的`apns-conf.xml`都在`/product/etc/apns-conf.xml`里面
我看了一下`functions.sh`，关于里面的225行
`q=$(find /system -name "apns-conf.xml" -type f)`
在crdroid、fluid的`/system`下根本搜不到`apns-conf.xml`，所以才显示不支持。
我把`functions.sh`和`install.sh`的`find /system`改成`find /product`以后，刷是能刷，不过一点效果没有😂

**Comment by RimuruW** [comment]
@D-Bood 
对于你的描述我有一些疑惑，希望你能提供更多的信息以帮助我们解决这个问题。

1. 根据我的认知，Android 根目录下的 `/product` 是挂载在 `/system` 下的。虽然我不认为这些 ROM 开发者会无聊到添加一个新的分区，但还是有必要确认一下，`/product` 是否有链接指向 `/system/product`？
![Screenshot](https://user-images.githubusercontent.com/59136309/115962712-3e3b3880-a54f-11eb-861a-724bd539ba1b.png)

2. 根据你的描述，我想确认一下 APN 配置文件是否是开机后由某个应用生成的（虽然这在逻辑上解释不通，但或许可以尝试一下）。你可以在 recovery 检查是否存在相应文件。

如果这个问题无法确定原因但确实存在相应 APN 配置文件，我可能会考虑加入「强制在所有可能位置放入 APN 配置文件」的选项。

最后，无论如何，感谢你的回复！

**Comment by RimuruW** [comment]
另外，`/product/etc/apns-conf.xml` 是早就确认可以正常替换的配置文件路径。我计划在近期刷入存在问题的 ROM 进行相关测试。

**Comment by D-Bood** [comment]
![Screenshot_20210424-225848_MT管理器](https://user-images.githubusercontent.com/19803652/115963099-df76be80-a550-11eb-9d60-83b5d58a69a7.png)
`/product`在crdroid里是个文件夹，不是链接
`apns-conf.xml`应该不是自动生成的。
感谢您的回复 @RiwiHow

**Comment by RiwiHow** [comment]
> ![Screenshot_20210424-225848_MT管理器](https://user-images.githubusercontent.com/19803652/115963099-df76be80-a550-11eb-9d60-83b5d58a69a7.png)
> `/product` 在 crdroid 里是个文件夹，不是链接
> `apns-conf.xml` 应该不是自动生成的。
> 感谢你的回复 @RiwiHow

应该感谢 @RimuruW ，是他回复的
由于技术细节我不太清楚，他这几天也没空，所以暂时解决不了。麻烦你等几天（五一就有时间了），谢谢！

**Comment by D-Bood** [comment]
实在太困了，给@错了，实在不好意思😂

**Comment by RiwiHow** [comment]
@bluboy-official @D-Bood 

抱歉，久等了。可以试一下[这个](https://github.com/RiwiHow/FixChinaCarrier/releases/tag/v5.3.0-beta.1)版本 😆
刷入重启后记得手动重置一下 APN 设置

**Comment by D-Bood** [comment]
@RiwiHow 感谢！但是测试起来好像还是没有效果。
![Screenshot_20210504-233609](https://user-images.githubusercontent.com/19803652/117029716-84538180-ad31-11eb-86ab-f7bf24d9050e.jpg)
我已经换了氧os，刷之前和之后的效果是一样的😂
我估计是分区保护的原因，因为不管氧os还是我刷过的几个系统，`/product`和`/system`分区都是只读，且无法挂载为读写

**Comment by RimuruW** [comment]
@D-Bood 不是所谓分区保护的原因。按照 Android 系统的设计，system 等重要分区默认都是只读。按照 Magisk 文档的描述，Magisk 会自动借助它的 Magic Mount 解决这个问题。

我猜测可能是因为 A/B 系统是双系统分区。但我手上没有系统是 A/B 分区的设备所以无法测试。

目前可能可行的方法是通过 Magisk 模块添加开机启动脚本，每次开机后覆盖 APN 相关文件，但是这样的话又需要手动修改 system 分区的权限，或许可能会影响系统正常运行或拖慢开机速度。如果你更好的解决思路，欢迎分享或提交 PR。

另外，你目前这个系统的 APN 配置似乎是正常的，你可以查看一下你相应目录下的 APN 配置文件是否已经替换为小米的 APN 配置文件。

**Comment by D-Bood** [comment]
@RimuruW 检查了，没有被替换。

**Comment by RimuruW** [comment]
@bluboy-official @D-Bood
可以试一下[这个](https://github.com/RiwiHow/FixChinaCarrier/releases/tag/v5.3.0-beta.4)版本，安装完点击右上角保存日志。

理论上无法替换，但是可以获取一些信息，不出意外下次更新就可以解决了。

**Comment by bluboy-official** [comment]
> @bluboy-official @D-Bood
> 可以试一下[这个](https://github.com/RiwiHow/FixChinaCarrier/releases/tag/v5.3.0-beta.4)版本，安装完点击右上角保存日志。
> 
> 理论上无法替换，但是可以获取一些信息，不出意外下次更新就可以解决了。

辛苦了！ 我这边已经更换其他的手机了 故不能测试 抱歉😂

**Comment by RimuruW** [comment]
@bluboy-official 没关系

**Comment by Gluneklairo** [comment]
> @bluboy-official @D-Bood
> 可以试一下[这个](https://github.com/RiwiHow/FixChinaCarrier/releases/tag/v5.3.0-beta.4)版本，安装完点击右上角保存日志。
> 
> 理论上无法替换，但是可以获取一些信息，不出意外下次更新就可以解决了。

[magisk_install_log_2021-05-31T09_32_57Z.log](https://github.com/RiwiHow/FixChinaCarrier/files/6567283/magisk_install_log_2021-05-31T09_32_57Z.log)

一加8T Evolution X Android 11
最新版仍然无法替换/product/etc/apns-conf.xml

**Comment by RiwiHow** [comment]
> > @bluboy-official @D-Bood
> > 可以试一下[这个](https://github.com/RiwiHow/FixChinaCarrier/releases/tag/v5.3.0-beta.4)版本，安装完点击右上角保存日志。
> > 理论上无法替换，但是可以获取一些信息，不出意外下次更新就可以解决了。
> 
> [magisk_install_log_2021-05-31T09_32_57Z.log](https://github.com/RiwiHow/FixChinaCarrier/files/6567283/magisk_install_log_2021-05-31T09_32_57Z.log)
> 
> 一加 8T Evolution X Android 11
> 最新版仍然无法替换 /product/etc/apns-conf.xml

抱歉，麻烦等几天，@RimuruW 和我最近没啥时间 😅

**Comment by RiwiHow** [comment]
@D-Bood @Gluneklairo 
久等了，可以试试这个[版本](https://github.com/RiwiHow/FixChinaCarrier/releases/tag/v5.3.1) 😆

**Comment by Gluneklairo** [comment]
> @D-Bood @Gluneklairo
> 久等了，可以试试这个[版本](https://github.com/RiwiHow/FixChinaCarrier/releases/tag/v5.3.1) 😆

成功了，好耶🥰
